### ISSUE TITLE
Stop Releasing Container Images with Commit SHA

### ISSUE THREAD

**Issue by rawkode** [packethost/packet-ccm#112]
As this project is consumed by customers, we should stop publishing each commit as a unique tag. This pollutes the tag list for customers and adds various layers of confusion to something that should be a simple `docker search`.

If we continue to release `main` / `master`, then this should be published using an mutable tag, such as `latest` - though its usage should be discouraged.

Each tagged release should be tagged with a semantic version.

**Comment by deitch** [comment]
I definitely understand your point, but don't completely agree. It does make it harder for consumers. However, we do generate the yaml for them as part of the github release page, e.g. see [v2.0.0](https://github.com/packethost/packet-ccm/releases/tag/v2.0.0). In theory, they shouldn't be looking at the docker hub page / `docker search`, except for more advanced users.

The more important point, though, is that we need a way to distribute "merged but not released" images. For example, we may be at release v2.0.0, and have 5 PRs merged in since then, but are not yet ready to cut a release. We need a way to be able to distribute and use images based on those changes. Hence the need to have those out there, solely hash-based. 

We do also push images for actual releases, so the [hub tags page](https://hub.docker.com/r/packethost/packet-ccm/tags?page=1&ordering=last_updated) has hash-tagged releases, but also semver releases.

Essentially, we rely on the GitHub releases page as the entrypoint for regular users, while the docker hub page (and `docker search`) are an entrypoint for more advanced users, as well as consumed by the releases artifacts (yaml).

**Comment by rawkode** [comment]
@deitch thanks for the extra context.

> The more important point, though, is that we need a way to distribute "merged but not released" images.

I'd love to understand the why for this?

**Comment by deitch** [comment]
> why for this?

Once something is merged in, it is considered "ready", even if it does not have a formal release. It may not have a release because we want to bundle it together with some other changes, or it may not have a formal release because it is ready for advanced users who are willing to take some risk, but not everyday users.

Either way, those need a way of getting at the ccm image with which to work.

**Comment by deitch** [comment]
Is this still relevant? Can we close this issue @rawkode ?

**Comment by rawkode** [comment]
@deitch I'd still like to discuss not doing this. If we feel that each merge to the main branch is "releaseable", then we should automate pushing patch releases with semantic versioning.

Commit shas are noisy and don't mean a great deal to the human eye, I think we can improve this experience for our end users.

Can we continue to discuss, please?

**Comment by deitch** [comment]
> If we feel that each merge to the main branch is "releaseable", then we should automate pushing patch releases with semantic versioning

That can get really messy. We want as small PRs as possible, which means we could have many many small ones, but only cut an actual semver one when ready.

> Commit shas are noisy and don't mean a great deal to the human eye, I think we can improve this experience for our end users.

I agree, they are noisy, but why would anyone be looking at the list of tags in docker hub? You need a lot to make this work, essentially the manifest. We auto-generate it for every semver release, including the right tag. 

So the only people looking directly on docker hub should be those who know what they are doing, and can filter for semver if they want.

Combine that with the need to actually have built images per merge-to-main, and this appears to be the best solution. 

Of course, if we can come up with a better one, I don't mind. But `v2.1.1657` doesn't really cut it:

* you end up with `v2.1.1657` is equal to `v2.2.0` which you manually tagged
* there is no obvious way to see from `v2.1.1657` that it is from commit `abcd1234` - the rare individuals who know that they want a specific mainline commit (and are capable of working with it) are going from a commit to a release
* automated tagging like that and manual tagging will come into conflict

I could see changing it to be, instead of the actual hash, something like `master-<hash>`, so it is clear what it is, but I am not convinced that addresses what you are raising.

**Comment by rawkode** [comment]
If anyone else comes across this issue at a later date, please reopen it.

@deitch @thebsdbox and myself had a chat and we do believe this can be a frustrating experience, but we do want to expose builds for each commit to consumers of the ccm. Docker Hub doesn't expose semantically versioned tags over arbitrary commit SHAs, so it will look a little weird when you try to find a tag.

We recommend using GitHub releases or filtering Docker Hub on "v" for the time being.

When someone else finds this frustrating, we'll look at putting in the required work to either move to another repository that better supports our use-case; or even publish commit SHAs to an alt image.
