### ISSUE TITLE
Reconsider MetalLB deployment management

### ISSUE THREAD

**Issue by displague** [packethost/packet-ccm#81]
The CCM's LoadBalancer feature, when enabled, creates and manages a MetalLB deployment. This includes the RBAC and service records.

While convenient, this managed installation expressing many opinions that are not configurable, including:
* namespace
* resource names
* RBAC settings
* all aspects of MetalLB configuration

Rather than managing the complete deployment, PacketCCM could offer an option to manage only the configmap used by a user-managed deployment.

* Remove deployment management (daemonset, services, rbac) for MetalLB resources from PacketCCM
* Remove RBAC packet-ccm uses in support of the controller management responsibility
* Keep ConfigMap management 
  * ConfigMap location should be a configuration option to the PacketCCM (PacketCCM's deployment would need to run with a clusterrole to access configmaps in any namespace)
  * ConfigMap type could be an option (to more easily support various versions of MetalLB or KubeVIP, assuming either can be managed by a single configmap)
  * ConfigMap management approach could be an option (patch vs create/replace, allowing users to provide base configuration that PacketCCM ignores)
* Optional Helm chart flags could be used to install MetalLB or KubeVIP
  * If we alternatively offer a kustomize based install, users could apply their own patches to the MetalLB yaml we provide
  * ^ may also be possible with Helm (I don't know Helm well enough to say)
  * Or these instructions could be left to the user, so the PacketCCM helm chart does not need to reproduce the helm chart of other applications. (the experience would be something like: helm install metallb; helm install packet-ccm --options-for-metallb)

---

Everything above still applies if we move to KubeVIP.

**Comment by deitch** [comment]
To summarize what you and I discussed earlier today. Let's make sure we are on the same page.

Right now, ccm gives you two options:

1. Deploy metallb and manage the configmap for you ("enable")
1. Do not deploy metallb or do anything with it ("disable")

The first option is for those who want "it just works"; the second is for those who already know how to manage metallb and want to do it their own way.

You are proposing a third option: manage the config only.

Customers would deploy metallb if/how/wherever they want. ccm would be responsible solely for managing the configmap, as it already has the logic to do that. Customer would provide the config namespace and name, and ccm would manage it.

Is that correct?

**Comment by displague** [comment]
@deitch, yes, that is how we discussed it.

I would perhaps, take it further, if possible.

I would take the "deploy metallb" responsibility out of the controller. MetalLB would be installed by Helm/Kustomize during the initial CCM install.

With that option I don't know if it would be better to use a separate (official) chart, or some MetalLB chart copy (maintained by us) included in the CCM's installation chart.  I would presume the former is better, but I'm not aware of the stability of that chart nor the kinds of changes that we make during installation.

My points in the issue description were made in consideration of this approach.
* The controller would need configuration parameters to identify the MetalLB (or perhaps KubeVIP) version.
* Overlay configuration options could be introduced (patch an existing or templated config, or create a new fully managed config)

**Comment by deitch** [comment]
> I would take the "deploy metallb" responsibility out of the controller. 

I don't agree with this for the simple reason that customers expect it to "just work". The assumption of CCM (not just Packet/EquinixMetal's, but in general), is that when I run a CCM, it sets up my loadbalancers. At EM, I need to do more work to enable those loadbalancers (install metallb) than I do at a hyperscaler (e.g. ELB is just there), but that doesn't change the expectation of user experience.

I agree wholeheartedly that there should be options to enable/disable deployment (which exists), and I very much like the idea of, "I am a more advanced user, I can deploy the prerequisites (metallb) on my own, but I want that great config management that CCM provides."

> MetalLB would be installed by Helm/Kustomize during the initial CCM install.

If helm/kustomize is the only way that people deploy things to k8s, then sure. The challenge is that the baseline remains kubectl, not helm or kustomize (and then kubectl). If it were, then the idea of abstracting the deployment of metallb from the deployment of ccm (i.e. making them parallel) would work really well.

On the other hand, something I could get behind (but would want to ask people like @enkelprifti98 or his peers for validation) is having two distinct deployment manifests for CCM, both available in [releases](https://github.com/packethost/packet-ccm/releases), where:

* file1 is CCM
* file2 B is CCM+loadbalancer

Or, perhaps alternatively:

* file1 is CCM
* file2 is loadbalancer

And we can tell customers that if you want CCM, do file1, CCM plus loadbalancer, do file2 (or file1 and file2, for the alternate option). This would be instead of the "disable loadbalancer" switch.

Perhaps that is what you were getting at?

**Comment by enkelprifti98** [comment]
I am okay with the idea of having 2 different files if it solves the issue that @displague is raising.

**Comment by displague** [comment]
> Perhaps that is what you were getting at?
You give me too much credit, this is yet another evolution.

> The challenge is that the baseline remains kubectl, not helm or kustomize (and then kubectl)
> And we can tell customers that if you want CCM, do file1, CCM plus loadbalancer, do file2 (or file1 and file2, for the alternate option). This would be instead of the "disable loadbalancer" switch.

Two files or more, for install, is what I was thinking.  The instructions would sew these together.

I also like your suggestion of alternate install URLs with seamless single URLs representing the intent to have both loadbalancer and ccm installed.

The main point is that MetalLB would be independent and "installed" (by our install yaml or by following our instructions) not dependent and "managed" (by our CCM controller).

I imagine install instructions like this:

* If you want to enable LoadBalancer instructions, Install MetalLB first, here are some methods to do that:
  * kubectl apply -f https://... # bare 
  * kubectl apply -k local_config_from_examples_or_clone.yaml # includes `bases: [ "our base" ]`

* Or you can install them together:
  * helm upgrade chart name --set loadbalancer.type=metallb --set loadbalancer.install=true --set loadbalancer.configPatch="$(cat my-config.yaml)"

* If you want to manage MetalLB yourself, just tell us where the confimap is (default is metallb.configsomething)
  * helm upgrade chart name --set loadbalancer.type=metallb --set loadbalancer.install=false --set loadbalancer.configMap=default.SelfInstalledMetalLB
  * kubectl apply -f https://.../ccm-and-loadbalancer-enabled.yaml 
  * kubectl apply -k example_that_include_above_as_base_and_modifies_configmap.yaml

I'll reach out for additional viewpoints, as I could be missing some of the benefits we enjoy and provide with the current approach.

**Comment by deitch** [comment]
I wrote the current approach, and I am pretty confident that the benefits we get from the current approach are:

* configmap management (which you already covered and included, so we are good)
* single easy deploy

I think we should go for the two files - combined and single - and instructions say, "use this one" or "use that one". Then you can set where the configmap to manage is, with the default matching what is in the combined deployment.

**Comment by deitch** [comment]
Resolved with #83
